### ISSUE TITLE
Unknown CUDA error

### ISSUE THREAD

**Issue by fineon** [pieroit/stable-diffusion-jupyterlab-docker#1]
Hi there,

I am trying to run Stable Diffusion on Docker container. I have run all the Jupyter cells till the prompt part, when it gives me this error below. I tried to rerun all cells to reimport token and model but the error is always the same. Not sure what's happening.

Cell: 
```python
prompt      = "chicken, art deco portrait, elegant, intricate, digital painting, artstation, concept art, smooth, sharp focus, illustration"
repetitions = 5

with autocast('cuda'):
    for r in range(repetitions):
        output = model(
            prompt,
            generator=seed_generator,
            num_inference_steps=50, # diffusion iterations
            guidance_scale=7.5,     # adherence to text, default 7.5
            width=512,
            height=512,
        )

        image = output['sample'][0]
        image.save(f'images/{time()}_{slugify(prompt[:100])}.png')
        display(image)
```

Output:
```text
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_33/1844182087.py in <module>
     10             guidance_scale=7.5,     # adherence to text, default 7.5
     11             width=512,
---> 12             height=512,
     13         )
     14 

/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/opt/conda/lib/python3.7/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py in __call__(self, prompt, height, width, num_inference_steps, guidance_scale, eta, generator, output_type, **kwargs)
    135 
    136             # predict the noise residual
--> 137             noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings)["sample"]
    138 
    139             # perform guidance

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py in forward(self, sample, timestep, encoder_hidden_states)
    149             if hasattr(downsample_block, "attentions") and downsample_block.attentions is not None:
    150                 sample, res_samples = downsample_block(
--> 151                     hidden_states=sample, temb=emb, encoder_hidden_states=encoder_hidden_states
    152                 )
    153             else:

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_blocks.py in forward(self, hidden_states, temb, encoder_hidden_states)
    503         for resnet, attn in zip(self.resnets, self.attentions):
    504             hidden_states = resnet(hidden_states, temb)
--> 505             hidden_states = attn(hidden_states, context=encoder_hidden_states)
    506             output_states += (hidden_states,)
    507 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py in forward(self, x, context)
    166         x = x.permute(0, 2, 3, 1).reshape(b, h * w, c)
    167         for block in self.transformer_blocks:
--> 168             x = block(x, context=context)
    169         x = x.reshape(b, h, w, c).permute(0, 3, 1, 2)
    170         x = self.proj_out(x)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py in forward(self, x, context)
    194 
    195     def forward(self, x, context=None):
--> 196         x = self.attn1(self.norm1(x)) + x
    197         x = self.attn2(self.norm2(x), context=context) + x
    198         x = self.ff(self.norm3(x)) + x

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py in forward(self, x, context, mask)
    252 
    253         # attention, what we cannot get enough of
--> 254         attn = sim.softmax(dim=-1)
    255 
    256         out = torch.einsum("b i j, b j d -> b i d", attn, v)

RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by pieroit** [comment]
Hi @fineon 

Does `torch.cuda.is_available()` give you `True`?
If yes try to lower image resolution, by changing `width` and `height`

**Comment by fineon** [comment]
Thanks for your suggestion! I tried to resize the width and height but it gave me a new error: 
```text
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_124/1145240200.py in <module>
     10             guidance_scale=7.5,     # adherence to text, default 7.5
     11             width=200,
---> 12             height=200,
     13         )
     14 

/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/opt/conda/lib/python3.7/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py in __call__(self, prompt, height, width, num_inference_steps, guidance_scale, eta, generator, output_type, **kwargs)
    135 
    136             # predict the noise residual
--> 137             noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings)["sample"]
    138 
    139             # perform guidance

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py in forward(self, sample, timestep, encoder_hidden_states)
    170                     temb=emb,
    171                     res_hidden_states_tuple=res_samples,
--> 172                     encoder_hidden_states=encoder_hidden_states,
    173                 )
    174             else:

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_blocks.py in forward(self, hidden_states, res_hidden_states_tuple, temb, encoder_hidden_states)
   1032             res_hidden_states = res_hidden_states_tuple[-1]
   1033             res_hidden_states_tuple = res_hidden_states_tuple[:-1]
-> 1034             hidden_states = torch.cat([hidden_states, res_hidden_states], dim=1)
   1035 
   1036             hidden_states = resnet(hidden_states, temb)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 7 for tensor number 1 in the list.
```

Meanwhile, I restarted the `download` jupyter book, the last prompt cell output an error: 
```
prompt = 'A puffy lazy cat sleeping on the couch, 8k'

with autocast('cuda'):
    output = model(prompt)
    
output['sample'][0]
```

Error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_85/1074367797.py in <module>
      2 
      3 with autocast('cuda'):
----> 4     output = model(prompt)
      5 
      6 output['sample'][0]

/opt/conda/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     25         def decorate_context(*args, **kwargs):
     26             with self.clone():
---> 27                 return func(*args, **kwargs)
     28         return cast(F, decorate_context)
     29 

/opt/conda/lib/python3.7/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py in __call__(self, prompt, height, width, num_inference_steps, guidance_scale, eta, generator, output_type, **kwargs)
    135 
    136             # predict the noise residual
--> 137             noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings)["sample"]
    138 
    139             # perform guidance

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py in forward(self, sample, timestep, encoder_hidden_states)
    149             if hasattr(downsample_block, "attentions") and downsample_block.attentions is not None:
    150                 sample, res_samples = downsample_block(
--> 151                     hidden_states=sample, temb=emb, encoder_hidden_states=encoder_hidden_states
    152                 )
    153             else:

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_blocks.py in forward(self, hidden_states, temb, encoder_hidden_states)
    503         for resnet, attn in zip(self.resnets, self.attentions):
    504             hidden_states = resnet(hidden_states, temb)
--> 505             hidden_states = attn(hidden_states, context=encoder_hidden_states)
    506             output_states += (hidden_states,)
    507 

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py in forward(self, x, context)
    166         x = x.permute(0, 2, 3, 1).reshape(b, h * w, c)
    167         for block in self.transformer_blocks:
--> 168             x = block(x, context=context)
    169         x = x.reshape(b, h, w, c).permute(0, 3, 1, 2)
    170         x = self.proj_out(x)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py in forward(self, x, context)
    194 
    195     def forward(self, x, context=None):
--> 196         x = self.attn1(self.norm1(x)) + x
    197         x = self.attn2(self.norm2(x), context=context) + x
    198         x = self.ff(self.norm3(x)) + x

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

/opt/conda/lib/python3.7/site-packages/diffusers/models/attention.py in forward(self, x, context, mask)
    252 
    253         # attention, what we cannot get enough of
--> 254         attn = sim.softmax(dim=-1)
    255 
    256         out = torch.einsum("b i j, b j d -> b i d", attn, v)

RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by fineon** [comment]
> Does torch.cuda.is_available() give you True

It does after running the cells

**Comment by fineon** [comment]
I fixed this issue by changing the output image size to a number that is a multiple of 64 (448px x448px).  Not sure if other encounters this problem as well but i hope it helps
